site_name: spring-boot-starter-influxdb
site_description: 
site_author: Hiberbee
repo_name: Hiberbee/spring-boot-starter-influxdb
repo_url: https://github.com/Hiberbee/spring-boot-starter-influxdb
copyright: 'Copyright &copy; 2019 Hiberbee'

theme: 'material'
extra:
  palette:
    primary: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/Askent'

google_analytics:
  - 'UA-134817745-1'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
  - Home: index.md
  - User guide:
      - Installation: guide/installation.md
  - About:
      - Release notes: about/history.md
